import React from 'react'




function about({params}) {
    console.log(params)
  return (
    <div>
      i am about page 
      {params.slug.map((item)=>{
        return <div key={item}>{item}</div>
      })}
      
    

    </div>
  )
}

export default about
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};