import React from 'react'



function page() {
  return (
    <div>
      contact
    </div>
  )
}

export default page
export const metadata = {
    title: "Contact",
    description: "Generated by create next app",
  };