import React from 'react'




function about() {
  return (
    <div>
      i am about
    </div>
  )
}

export default about
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};